### ISSUE TITLE
how to access the dashboard

### ISSUE THREAD

**Issue by Roundhead22** [jaomaloy/balena-rtl-power#2]
how and where do i access the dashboard

**Comment by jaomaloy** [comment]
@Roundhead22, To access the Grafana dashboard, please refer to the [Viewing the heatmap](https://github.com/jaomaloy/balena-rtl-power#viewing-the-heatmap) section of the README.

To access the balena dashboard to create your fleet or to manage your devices. Referring to the [Deploying the fleet](https://github.com/jaomaloy/balena-rtl-power#deploying-the-fleet) section of the README might help. Thanks :smile: 

https://github.com/jaomaloy/balena-rtl-power/commit/77d1b8e9b40e804ce9b8fab26ec7560c8327b1e6
